// SERVED MODEL: claude-opus-5[1m]
//
// X.P.W2.d — AC-1 TAGLESS-TWIN · THE BUILD, WHICH IS `node` AND NOTHING ELSE (K-9).
//
//   node experiments/w2/ac1-tagless/build.mjs
//
// It writes three artifacts and reads no toolchain: `build/ac1.wasm` (the emitted module's bytes,
// produced by `lowering-wasm/index.mjs` — the same bytes the adapter instantiates), `build/ac1.js`
// (the JS artifact: the slice's three entries over the JS lowering) and `build/ac1.d.ts` (the frozen
// declaration, RE-EXPORTED from the vendored 4.0.0 rather than re-typed — a second copy of a frozen
// surface is the shape the whole tranche exists to stop).

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { buildModule } from "./lowering-wasm/index.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "build");
const VENDORED_CSS_DTS =
    "/Users/mkbabb/Programming/value.js/docs/tranches/V/megatranche/prototypes/css-parser/cand-o/vendor/value-js-4.0.0/dist/subpaths/css";

/**
 * X.P.W4.e — C3 (COHESION §0y F-w4b-3). THE FROZEN SURFACE BECOMES THE PACKAGE'S OWN BYTES.
 *
 * Until this landed, `ac1.d.ts` re-exported the thirty-three frozen names through a RELATIVE
 * SPECIFIER THAT LEFT THE PACKAGE ROOT — `../../../../../value.js/docs/…/vendor/value-js-4.0.0/dist/
 * subpaths/css`. Inside this repository that path exists and the declaration type-checks; inside a
 * consumer's `node_modules` it addresses a directory five levels above the package that has no
 * reason to exist, so every one of the thirty-three types resolved in the source tree and in no
 * tarball. That is precisely G-3's falsifier — *"a symbol that resolves in the source tree and not
 * in the tarball fails"* — and the cure is not a longer path but the absence of one: the build
 * BYTE-COPIES the pinned declaration INTO the package and `ac1.d.ts` re-exports from that copy.
 *
 * SHA-PINNED, and the pin is enforced rather than recited: `VENDORED_CSS_DTS_SHA256` is the value
 * X.P.W3's own artefacts record for this file (`evidence/W3/universe-52.json` `.frozen.sha256`,
 * `evidence/W3/equivalence-full-surface.json` `.declarationSha256`). The build HALTS if the source
 * declaration's bytes no longer hash to it — a copy taken from a drifted original would make the
 * package's own surface disagree with the universe every gate is measured against, silently. The
 * sha is written into the emitted file's header so the copy carries its own provenance.
 *
 * The copy is a BYTE COPY: the vendored declaration's bytes are appended verbatim beneath a comment
 * header. Nothing is re-typed, re-ordered or re-formatted — a second, hand-maintained spelling of a
 * frozen surface is the exact shape this tranche exists to stop (see this file's own header).
 */
const VENDORED_CSS_DTS_FILE = `${VENDORED_CSS_DTS}.d.ts`;
const VENDORED_CSS_DTS_SHA256 = "c81d095213d112c6bdbddf1ddb65da2a1286d6e2ff37f5f0ba40e78a439743d0";
/** The in-package name of the copy; `.js` is how a NodeNext `.d.ts` addresses a sibling `.d.ts`. */
const FROZEN_DTS_BASENAME = "value-css-4.0.0.d.ts";
const FROZEN_DTS_SPECIFIER = "./value-css-4.0.0.js";

mkdirSync(OUT, { recursive: true });

const built = buildModule();
writeFileSync(path.join(OUT, "ac1.wasm"), Buffer.from(built.bytes));

/**
 * X.P.W3.h — the JS artifact is the PUBLIC SURFACE (`entry.mjs`), re-exported by name: the six
 * grammar entries (the slice's three and the value grammar's three) at the boundary `.c` gives
 * them, and the two compositions on that surface (`coerceToSyntax`, `serializeCssColor`). Until
 * this landed the artifact reached the raw lowering (`L.entry(…)`) beneath the public entry, so a
 * consumer of the artifact and a consumer of `entry.mjs` were two surfaces; they are one.
 */
const RUNTIME_EXPORTS = [
    "parseCssColor", "parseTimingFunction", "parseStylesheet",
    "parseCssScalar", "parseCssValue", "parseCssValues",
    "coerceToSyntax", "serializeCssColor",
    // X.P.W3.i — the animation family: three grammar entries and three structured compositions
    "parseKeyframeSelector", "parseAnimationTimeline", "parseAnimationRange",
    "serializeTimelineOptions", "collectAnimationOptions", "collectTimelineOptions",
    // X.P.W3.j — the five stylesheet collectors; with these the artifact names all NINETEEN
    // frozen runtime exports of `src/css/index.ts`, and the barrel's runtime half is closed.
    "collectDeclarations", "collectStyleRules", "collectKeyframes",
    "collectPropertyDescriptors", "collectCustomFunctions",
];

writeFileSync(
    path.join(OUT, "ac1.js"),
    `// SERVED MODEL: claude-fable-5-1
//
// GENERATED by \`build.mjs\` — the JS artifact of AC-1 TAGLESS-TWIN: the public surface of
// \`entry.mjs\` over the JS lowering, at the boundary BND-1 gives it (X.P.W3.c), by name.

export {
${RUNTIME_EXPORTS.map((name) => `    ${name},`).join("\n")}
} from "../entry.mjs";
`,
);

//  C3 — the frozen declaration, byte-copied into the package under its recorded sha.
const frozenBytes = readFileSync(VENDORED_CSS_DTS_FILE);
const frozenSha256 = createHash("sha256").update(frozenBytes).digest("hex");
if (frozenSha256 !== VENDORED_CSS_DTS_SHA256) {
    throw new Error(
        `HALT: the vendored 4.0.0 declaration is not the pinned one.\n`
        + `  file     ${VENDORED_CSS_DTS_FILE}\n`
        + `  pinned   ${VENDORED_CSS_DTS_SHA256}\n`
        + `  measured ${frozenSha256}\n`
        + `The frozen surface every gate is measured against would be copied from a drifted `
        + `original. Re-pin deliberately (X.P.W3 evidence/W3/universe-52.json) or restore the file.`,
    );
}
writeFileSync(
    path.join(OUT, FROZEN_DTS_BASENAME),
    `// SERVED MODEL: claude-opus-5[1m]
//
// GENERATED by \`build.mjs\` (X.P.W4.e, C3). A BYTE COPY of the sha-pinned vendored 4.0.0 \`/css\`
// declaration — \`@mkbabb/value.js@4.0.0\`'s own \`dist/subpaths/css.d.ts\` — carried INSIDE this
// package so the frozen surface resolves from a consumer's \`node_modules\` and not only from this
// repository's tree (G-3's falsifier). Nothing below is re-typed: the bytes beneath this header are
// the source file's, verbatim.
//
//   source  ${VENDORED_CSS_DTS_FILE}
//   sha256  ${frozenSha256}
//   bytes   ${frozenBytes.length}
//
// Regenerate with \`node src/css/build.mjs\`; the build HALTS if the source's sha256 ever differs
// from the pin recorded in \`build.mjs\`, so this copy cannot silently follow a drifted original.

`,
);
writeFileSync(path.join(OUT, FROZEN_DTS_BASENAME), frozenBytes, { flag: "a" });

/** The frozen type names the artifact re-exports — the slice's five, X.P.W3.h's four, X.P.W3.i's fifteen. */
const TYPE_EXPORTS = [
    "CssColor", "CssTimingFunction", "Stylesheet", "StyleRule", "Declaration",
    "CssColorSpace", "CssLinearStop", "ParseIssue", "ParseResult",
    // X.P.W3.i — the fifteen animation / timeline / range / trigger / view types
    "AnimationRangeValue", "AnimationTimelineValue", "AnimationTriggerValue",
    "CSSAnimationOptions", "CSSTimelineOptions", "KeyframeSelector",
    "RangeBoundary", "RangePhase", "ScrollTimelineDescriptor", "ScrollerKeyword",
    "TimelineAxis", "TimelineScopeValue", "TriggerType", "ViewInset", "ViewTimelineDescriptor",
    // X.P.W3.j — the nine stylesheet types; with these the artifact re-exports all THIRTY-THREE
    // frozen type names, and the barrel's type half is closed.
    "CollectedRule", "KeyframeRule", "KeyframesBlock", "PropertyRule", "StylesheetItem",
    "CSSPropertyDescriptor", "CustomFunctionDescriptor", "CustomFunctionParameter", "CustomFunctionRule",
];
writeFileSync(
    path.join(OUT, "ac1.d.ts"),
    `// SERVED MODEL: claude-opus-5[1m]
//
// GENERATED by \`build.mjs\`. The frozen surface is the vendored, sha-pinned 4.0.0's own
// declaration; this file RE-EXPORTS it from the package's OWN copy of those bytes
// (\`${FROZEN_DTS_BASENAME}\`, sha256 ${frozenSha256}), emitted beside this file by the same build.
//
// X.P.W4.e / C3: the specifier below NEVER LEAVES THE PACKAGE ROOT. Its predecessor climbed five
// directories into another repository's vendor tree, which resolved in this working copy and in no
// tarball — so the thirty-three frozen types type-checked here and vanished in a consumer. A
// package's declaration may only address bytes the package ships.

export type { ${TYPE_EXPORTS.join(", ")} } from "${FROZEN_DTS_SPECIFIER}";
`,
);

console.log(`ac1.wasm   ${built.bytes.length} bytes · ${built.builder.funcs.length} functions · ${built.staticBytes} bytes of static data`);
console.log(`ac1.js     ${built.entries.join(" · ")}`);
console.log(`${FROZEN_DTS_BASENAME}   ${frozenBytes.length} bytes byte-copied · sha256 ${frozenSha256}`);
console.log(`ac1.d.ts   ${TYPE_EXPORTS.length} frozen types re-exported from ${FROZEN_DTS_SPECIFIER}`);
