lengthUnit = "px" | "cm" | "mm" | "Q" | "in" | "pc" | "pt" | "em" | "ex" | "ch" 
	| "rem" | "lh" | "rlh" | "vw" | "vh" | "vmin" | "vmax" | "vb" | "vi" 
	| "svw" | "svh" | "lvw" | "lvh" | "dvw" | "dvh" ;

angleUnit = "deg" | "rad" | "grad" | "turn" ;
timeUnit = "s" | "ms" ;
resolutionUnit = "dpi" | "dpcm" | "dppx" ;

percentageUnit = "%" ;
length = number , lengthUnit ;
angle = number , angleUnit ;

time = number , timeUnit ;
resolution = number , resolutionUnit ;
percentage = number , percentageUnit ;

valueUnit = length | angle | time | resolution | percentage | ( number , epsilon ) ;
