PROPERTY_VALUE = [ IDENT | NUMBER | STRING | PERCENTAGE | DIMENSION | FUNCTION | HASH 
	
	| INCLUDES | DASHMATCH 
	|  "!" , S , IMPORTANT_SYM ] , { S , [ IDENT 
	| NUMBER | STRING | PERCENTAGE | DIMENSION | FUNCTION 
	
	| HASH 
	| UNICODE_RANGE | INCLUDES | DASHMATCH | "!" , S , IMPORTANT_SYM ] } ;
