// biiiiiiiiig vibes
null = "null" ;
bool = "true" | "false" ;

// yeah man i'm str8 up a vibing human
// that's really just going for it

number = /-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\d+)?/ ; // oh wow ;

char = /[^"'\\]+/ | /\\"/ | /\\'/ | /\\\\/ ; // ' fixed dat lol
string = '"' >> char /*" i'm a vibe machine "*/ << '"' | "'" >> char << "'" ;
array = "[" >> ( value << ","? ) * << "]" ;

pair = string, ":" >> value ;
object = "{" >> ( pair << ","? ) * << "}" ;

value = null | bool | number | string | array | object ;

// and done