// biiiiiiiiig vibes
null = /*a*/   "null"  /*a*/   ;
bool = /*a*/ /*a*/ /*a*/ "true" /*a*/ | /*a*/  "false" ;

// yeah man i'm str8 up a vibing human
// that's really just going for it /*a*/

number = /*a*/  /-?(0|[1-9]\d*)(\.\d+)?([eE][+-]?\d+)?/ ; // oh wow ;

char = /[^"'\\]+/ | /\\"/ | /\\'/ | /\\\\/ ; // ' fixed dat lol
string = '"' >> /*a*/ char /*a*/ << '"' | "'" >> char << "'" ; // now that's 
array = /*a

biiiiiiiiig vibes

*/

"[" >> ( value << ","? ) * << "]" ;

pair = string, /*a*/ ":" /*a*/ >> /*a*/ value ;
object = "{" >> ( pair << ","? ) * << "}" ;

value = /*a*/ /*a*/ /*a*/ null | bool | number | string | array | object ;

// and done !