// SERVED MODEL: claude-opus-5[1m]
//
// X.P.W3.a — THE 33 TYPE ROWS, BY BIDIRECTIONAL ASSIGNABILITY, IN ONE COMPILE.
//
// `W3.md` §3 item 3: "Drive every type export to **TOTAL** by bidirectional assignability under
// `tsc --noEmit`, so a widened or narrowed candidate type fails the compile rather than passing a
// name check." §6 G-1: "33 types by bidirectional assignability in one compile."
//
// THE TWO SIDES.
//   FROZEN     the vendored, sha-pinned published 4.0.0 `/css` declaration, COPIED into
//              `generated/frozen-4.0.0.d.ts` with its sha256 asserted. Copied rather than
//              referenced across seven directory levels because that is precisely the defect
//              X.P.W3.0 had to cure at `ac1.d.ts` (K.8 D-c1): a specifier that resolves from one
//              checkout of a tree and not from another. A generated file regenerated from a pinned
//              source is location-independent by construction.
//              `pin.mjs::agreement()` separately PROVES this declaration stands in faithfully for
//              the pinned `src/css/types.ts`, by name and by member/literal set, so the copy is a
//              stand-in that has been checked rather than assumed.
//   CANDIDATE  whatever declaration surface the candidate's adapter declares
//              (`meta.artifacts.dts`), imported at its own path so its own relative specifiers
//              resolve the way the candidate ships them.
//
// THE ASSERTION, per frozen type `T`, is two ordinary assignments and nothing cleverer:
//     declare const c_T: Candidate.T;  const to_frozen_T: Frozen.T = c_T;      // candidate → frozen
//     declare const f_T: Frozen.T;     const to_candidate_T: Candidate.T = f_T; // frozen → candidate
// A NARROWED candidate type fails the second; a WIDENED one fails the first. A conditional
// `extends` probe would report `false` instead of failing, which is how a name check disguises
// itself as a shape check — so no conditional type appears here.
//
// ERRORS ARE ATTRIBUTED BY LINE, through a generated line map, so the matrix can say WHICH row
// failed rather than "the compile is red".

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { P2_ROOT, PUBLISHED_400_DTS, sha256 } from "./pin.mjs";

export const CSS_TOTALITY_DIR = path.join(P2_ROOT, "typescript/test/css-totality");
export const GENERATED_DIR = path.join(CSS_TOTALITY_DIR, "generated");
export const FROZEN_COPY = path.join(GENERATED_DIR, "frozen-4.0.0.d.ts");
export const GENERATED_TS = path.join(GENERATED_DIR, "assignability.generated.ts");
export const LINE_MAP = path.join(GENERATED_DIR, "assignability.map.json");
export const TSCONFIG = path.join(CSS_TOTALITY_DIR, "tsconfig.assignability.json");

const BANNER = (what, provenance) =>
    [
        "// SERVED MODEL: claude-opus-5[1m]",
        "//",
        `// GENERATED by \`typescript/scripts/css-universe.mjs\` — ${what}.`,
        `// Provenance: ${provenance}`,
        "// NEVER HAND-EDITED: the generator re-emits this file and `--check` fails on any drift.",
        "",
    ].join("\n");

/**
 * A type instantiation that is a TYPE. `ParseResult<T>` unapplied is not one, and skipping it would
 * quietly drop a row; `CollectedRule`'s parameter is defaulted, so it stands alone.
 * The argument is SIDE-AWARE — `Frozen.ParseResult<Frozen.Declaration>` against
 * `Candidate.ParseResult<Candidate.Declaration>` — because an unqualified argument is not in scope
 * in a module that imports both surfaces as namespaces, and qualifying it to one side would test
 * that side against itself.
 */
const INSTANTIATION = { ParseResult: (ns) => `<${ns}.Declaration>` };

/** Emit the candidate/frozen pair for one type, and record the lines the assertions land on. */
const assertionsFor = (name, startLine) => {
    const applied = (ns) => `${ns}.${name}${INSTANTIATION[name] ? INSTANTIATION[name](ns) : ""}`;
    const lines = [
        `// ── ${name} ──────────────────────────────────────────────────────────`,
        `declare const c_${name}: ${applied("Candidate")};`,
        `export const to_frozen_${name}: ${applied("Frozen")} = c_${name};`,
        `declare const f_${name}: ${applied("Frozen")};`,
        `export const to_candidate_${name}: ${applied("Candidate")} = f_${name};`,
        "",
    ];
    return {
        lines,
        // The two assignment lines, 1-indexed, in the emitted file.
        map: { toFrozen: startLine + 2, toCandidate: startLine + 4, declares: [startLine + 1, startLine + 3] },
    };
};

/**
 * Generate the frozen copy, the assignability program, its line map and its tsconfig.
 * Returns the paths and the sha256 of every generated byte.
 */
export const generate = ({ types, candidateDts }) => {
    mkdirSync(GENERATED_DIR, { recursive: true });

    const frozenText = readFileSync(PUBLISHED_400_DTS, "utf8");
    const frozenCopy =
        BANNER(
            "the FROZEN side of the assignability compile",
            `${PUBLISHED_400_DTS} — sha256 ${sha256(frozenText)}`,
        ) + frozenText;
    writeFileSync(FROZEN_COPY, frozenCopy);

    const candidateSpecifier = path
        .relative(GENERATED_DIR, candidateDts.replace(/\.d\.ts$/, ""))
        .split(path.sep)
        .join("/");

    const head = [
        BANNER(
            "the 33 frozen type rows, each asserted in BOTH directions",
            "the type names come from `src/css/index.ts` at the pinned value.js commit; the frozen shapes from the sha-pinned published 4.0.0 declaration",
        ),
        `import type * as Frozen from "./frozen-4.0.0";`,
        `import type * as Candidate from "${candidateSpecifier.startsWith(".") ? candidateSpecifier : `./${candidateSpecifier}`}";`,
        "",
    ].join("\n");

    const body = [];
    const map = {};
    let line = head.split("\n").length; // 1-indexed line of the last head line
    for (const name of types) {
        const emitted = assertionsFor(name, line);
        body.push(...emitted.lines);
        map[name] = emitted.map;
        line += emitted.lines.length;
    }

    const program = head + body.join("\n") + "\n";
    writeFileSync(GENERATED_TS, program);
    writeFileSync(LINE_MAP, `${JSON.stringify({ file: "assignability.generated.ts", rows: map }, null, 4)}\n`);

    const tsconfig = {
        _: "GENERATED by typescript/scripts/css-universe.mjs — G-1's assignability project. Standalone on purpose: the workspace tsconfig includes src/ and test/ wholesale, whose pre-existing errors would drown the 33 readings this compile exists to take.",
        compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            lib: ["ES2022", "ES2023"],
            strict: true,
            exactOptionalPropertyTypes: false,
            noEmit: true,
            skipLibCheck: true,
            forceConsistentCasingInFileNames: true,
            types: [],
        },
        include: ["generated/assignability.generated.ts"],
    };
    writeFileSync(TSCONFIG, `${JSON.stringify(tsconfig, null, 4)}\n`);

    return {
        frozenCopy: { path: FROZEN_COPY, sha256: sha256(frozenCopy), bytes: Buffer.byteLength(frozenCopy) },
        program: { path: GENERATED_TS, sha256: sha256(program), bytes: Buffer.byteLength(program) },
        map: { path: LINE_MAP, rows: map },
        tsconfig: { path: TSCONFIG },
        candidateSpecifier,
    };
};

/** `file(line,col): error TSxxxx: message` — tsc's own pretty-off output. */
const DIAGNOSTIC = /^(.+?)\((\d+),(\d+)\): error (TS\d+): (.*)$/;

/**
 * Run the one compile and attribute every diagnostic to its row. A diagnostic that lands outside
 * every row's lines is reported under `unattributed` rather than silently dropped — an error the
 * matrix cannot place is a finding, not noise.
 */
export const compile = (generated, types) => {
    let stdout = "";
    let exitCode = 0;
    try {
        stdout = execFileSync(
            "npx",
            ["tsc", "--noEmit", "--pretty", "false", "-p", path.relative(P2_ROOT, TSCONFIG)],
            { cwd: P2_ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
        );
    } catch (error) {
        stdout = `${error.stdout ?? ""}${error.stderr ?? ""}`;
        exitCode = error.status ?? 1;
    }

    const rows = Object.fromEntries(types.map((name) => [name, { cellsRun: 2, errors: [] }]));
    const unattributed = [];
    for (const raw of stdout.split("\n")) {
        const match = DIAGNOSTIC.exec(raw.trim());
        if (!match) continue;
        const [, file, lineText, , code, message] = match;
        const line = Number(lineText);
        const owner = types.find((name) => {
            const m = generated.map.rows[name];
            return (
                m &&
                (line === m.toFrozen ||
                    line === m.toCandidate ||
                    m.declares.includes(line))
            );
        });
        const entry = { code, message, line, file: path.basename(file) };
        if (owner) rows[owner].errors.push(entry);
        else unattributed.push(entry);
    }

    // A row whose `import type * as Candidate` cannot even resolve the name loses BOTH cells.
    // TS2724 is TS2694's "did you mean …" variant and means exactly the same thing — omitting it
    // would leave an unresolvable row claiming two executed cells.
    const UNRESOLVED = ["TS2694", "TS2305", "TS2724"];
    for (const name of types) {
        if (rows[name].errors.some((e) => UNRESOLVED.includes(e.code))) rows[name].cellsRun = 0;
    }

    return { exitCode, stdout, rows, unattributed };
};

/** Names the candidate's declaration surface actually exports. */
export const declaredTypeNamesOf = (candidateDtsText) => [
    ...new Set([
        ...[...candidateDtsText.matchAll(/export\s+(?:declare\s+)?(?:type|interface)\s+([A-Za-z_$][\w$]*)/g)].map(
            (m) => m[1],
        ),
        ...[...candidateDtsText.matchAll(/export\s+type\s*\{([^}]*)\}/g)].flatMap((m) =>
            m[1]
                .split(",")
                .map((s) => s.trim())
                .filter(Boolean)
                .map((s) => {
                    const as = /^(\S+)\s+as\s+(\S+)$/.exec(s);
                    return as ? as[2] : s;
                }),
        ),
    ]),
];
